networks:
    tweets-consumer-network:
        driver: bridge

services:
    rabbitmq:
        image: "rabbitmq:3-management"
        hostname: rabbitmq
        privileged: true
        ports:
            - "5672:5672"
            - "15672:15672"
        deploy:
            resources:
                limits:
                    memory: 500M
        networks:
            - tweets-consumer-network

    classificador:
        image: diogorodriguees/comunicacao-indireta:classificador
        restart: always
        deploy:
            replicas: 2
            resources:
                limits:
                    memory: 200M
        depends_on:
            - rabbitmq
            - coletor
        networks:
            - tweets-consumer-network

    coletor:
        image: diogorodriguees/comunicacao-indireta:coletor
        hostname: coletor
        depends_on:
            - rabbitmq
        restart: always
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 100M
        networks:
            - tweets-consumer-network
