# Etapa de build
FROM golang:1.22-alpine AS builder

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de configuração do Go
COPY go.mod .
COPY go.sum .

# Faz o download das dependências
RUN go mod download

# Copia o código-fonte para dentro do contêiner
COPY . .

# Compila a aplicação
RUN go build -o coletor

# Etapa de produção
FROM alpine:latest

# Cria um diretório de trabalho
WORKDIR /root/

# Copia o binário compilado da etapa de build
COPY --from=builder /app/coletor .

# Expõe a porta que a aplicação vai usar
EXPOSE 8080

# Define o comando para rodar a aplicação
CMD ["./coletor"]
